version: '3'
services:
  app:
    restart: always
    build: .
    container_name: 'python3'
    tty: true
    volumes:
      - .:/22_proken_python
  db:
    image: postgres
    volumes:
      - .:/22_proken_python
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: password

