version: '3'
services:
  app:
    restart: always
    container_name: solve_app
    build: .
    tty: true
    ports:
      - "8080:3000"
    volumes:
      - .:/22_proken_python
  db:
    image: postgres
    container_name: solve_db
    volumes:
      - .:/22_proken_python
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: password

