version: '3'
services:
  app:
    restart: always
    container_name: solve_app
    build: .
    container_name: 'python3'
    tty: true
    volumes:
      - .:/22_proken_python
  db:
    image: postgres
    container_name: solve_db
    volumes:
      - .:/22_proken_python
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: password

